/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package billmanage;

import billmanage.Bill;
import billmanage.Bill;
import billmanage.BillList;
import billmanage.BillList;
import java.awt.Menu;
import billmanage.UpdateBill;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class Menu1 extends javax.swing.JFrame {

    ArrayList<Bill> brr = new ArrayList<>();
    DefaultTableModel model;

    public ArrayList<Bill> getBrr() {
        return brr;
    }

    public void setBrr(ArrayList<Bill> brr) {
        this.brr = brr;
    }

    /**
     * Creates new form Menu1
     */
    public Menu1() {
        initComponents();
        this.setLocationRelativeTo(null);
        brr = new ArrayList<>();
        model = (DefaultTableModel) jTable1.getModel();
        
    }
      public void ReadOject() {
        BillList p = new BillList();
        brr.addAll(p.ReadBill());
        for(int i=0;i<brr.size();i++)
        {
            showTable(brr.get(i));
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtOldindex = new javax.swing.JTextField();
        txtNewindex = new javax.swing.JTextField();
        txtCode = new javax.swing.JTextField();
        btnAddbill = new javax.swing.JButton();
        btnResetAddbill = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        txtCodeRemove = new javax.swing.JTextField();
        btnDeleteBill = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        btnFindMax = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        btncompute = new javax.swing.JButton();
        ResetCompute = new javax.swing.JButton();
        txtResultSum = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtResultFindBill = new javax.swing.JTextArea();
        btnsearch = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        cbxType = new javax.swing.JComboBox<>();
        cbxchecktpye = new javax.swing.JComboBox<>();
        txtcodefind = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        jSeparator7 = new javax.swing.JSeparator();
        cbxMinMax = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SỬ DỤNG DỮ LIỆU CŨ");
        setLocation(new java.awt.Point(0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray, java.awt.Color.darkGray));
        jPanel1.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN  LÍ DANH SÁCH HÓA ĐƠN ");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Mã hóa đơn :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 99, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Loại hóa đơn :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 99, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Chỉ số cũ :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, 99, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Chỉ số mới :");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, 99, -1));

        txtOldindex.setBackground(new java.awt.Color(204, 255, 255));
        txtOldindex.setForeground(new java.awt.Color(0, 0, 0));
        txtOldindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldindexActionPerformed(evt);
            }
        });
        getContentPane().add(txtOldindex, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 95, 30));

        txtNewindex.setBackground(new java.awt.Color(204, 255, 255));
        txtNewindex.setForeground(new java.awt.Color(0, 0, 0));
        txtNewindex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewindexActionPerformed(evt);
            }
        });
        getContentPane().add(txtNewindex, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 110, 30));

        txtCode.setBackground(new java.awt.Color(204, 255, 255));
        txtCode.setForeground(new java.awt.Color(0, 0, 0));
        txtCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeActionPerformed(evt);
            }
        });
        getContentPane().add(txtCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 97, 30));

        btnAddbill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnAddbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/data-add-icon.png"))); // NOI18N
        btnAddbill.setText("Thêm");
        btnAddbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddbillActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 370, 100, 40));

        btnResetAddbill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnResetAddbill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/12125-eye-icon.png"))); // NOI18N
        btnResetAddbill.setText("Tải lại");
        btnResetAddbill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetAddbillActionPerformed(evt);
            }
        });
        getContentPane().add(btnResetAddbill, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 370, 110, -1));

        jTable1.setBackground(new java.awt.Color(255, 255, 204));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã hóa đơn", "Loại hóa đơn", "Chỉ số cũ", "Chỉ số mới", "Thanh toán"
            }
        ));
        jTable1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jTable1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 47, 1260, 200));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 320, 590, 11));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("MÃ HÓA ĐƠN CẦN XÓA :");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 180, 20));

        txtCodeRemove.setBackground(new java.awt.Color(204, 255, 255));
        txtCodeRemove.setForeground(new java.awt.Color(0, 0, 0));
        txtCodeRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCodeRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(txtCodeRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 280, -1));

        btnDeleteBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnDeleteBill.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-trash-empty-icon.png"))); // NOI18N
        btnDeleteBill.setText("Xóa");
        btnDeleteBill.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnDeleteBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBillActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteBill, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 440, 100, 40));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 241, 1250, 10));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("HÓA ĐƠN CÓ THANH TOÁN ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 270, 210, -1));

        btnFindMax.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnFindMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom-icon.png"))); // NOI18N
        btnFindMax.setText("Tìm kiếm");
        btnFindMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindMaxActionPerformed(evt);
            }
        });
        getContentPane().add(btnFindMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 260, 120, 40));

        jSeparator5.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator5.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 62, 1254, -1));

        btncompute.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btncompute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Calculator-icon.png"))); // NOI18N
        btncompute.setText("Tính");
        btncompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncomputeActionPerformed(evt);
            }
        });
        getContentPane().add(btncompute, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 570, 100, -1));

        ResetCompute.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ResetCompute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Button-Refresh-icon.png"))); // NOI18N
        ResetCompute.setText("Làm mới");
        ResetCompute.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        ResetCompute.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        ResetCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetComputeActionPerformed(evt);
            }
        });
        getContentPane().add(ResetCompute, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 120, 40));

        txtResultSum.setEditable(false);
        txtResultSum.setBackground(new java.awt.Color(153, 255, 204));
        txtResultSum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtResultSum.setForeground(new java.awt.Color(0, 0, 255));
        txtResultSum.setToolTipText("");
        getContentPane().add(txtResultSum, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 540, 280, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("KẾT QUẢ TỔNG HÓA ĐƠN THEO LOẠI :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, 270, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText(" LOẠI HÓA ĐƠN :");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 290, -1));
        getContentPane().add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 490, 650, 10));

        jButton5.setBackground(new java.awt.Color(102, 102, 102));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 10, 360));

        jButton6.setBackground(new java.awt.Color(102, 255, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 204, 0));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Go-back-icon.png"))); // NOI18N
        jButton6.setText("Trở lại");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, -1, 40));

        jButton7.setBackground(new java.awt.Color(102, 255, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 0, 51));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iconexit.png"))); // NOI18N
        jButton7.setText("Exit");
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 620, -1, 40));

        jLabel10.setBackground(new java.awt.Color(102, 102, 102));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("MÃ HÓA ĐƠN CẦN TÌM :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 340, 290, 30));

        txtResultFindBill.setEditable(false);
        txtResultFindBill.setBackground(new java.awt.Color(153, 255, 204));
        txtResultFindBill.setColumns(20);
        txtResultFindBill.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtResultFindBill.setForeground(new java.awt.Color(0, 0, 204));
        txtResultFindBill.setRows(5);
        jScrollPane2.setViewportView(txtResultFindBill);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 330, 180));

        btnsearch.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Zoom-icon.png"))); // NOI18N
        btnsearch.setText("Tìm kiếm");
        btnsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnsearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 390, 120, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 610, 1260, 10));

        cbxType.setBackground(new java.awt.Color(204, 204, 255));
        cbxType.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxType.setForeground(new java.awt.Color(0, 0, 0));
        cbxType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NN", "SX", "KD", "Khác" }));
        getContentPane().add(cbxType, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 110, 30));

        cbxchecktpye.setBackground(new java.awt.Color(204, 204, 255));
        cbxchecktpye.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cbxchecktpye.setForeground(new java.awt.Color(0, 0, 0));
        cbxchecktpye.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NN", "SX", "KD", "Khác" }));
        getContentPane().add(cbxchecktpye, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 500, 90, 30));

        txtcodefind.setBackground(new java.awt.Color(204, 255, 255));
        txtcodefind.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtcodefind.setForeground(new java.awt.Color(255, 0, 51));
        txtcodefind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodefindActionPerformed(evt);
            }
        });
        getContentPane().add(txtcodefind, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 340, 140, 30));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Actions-document-edit-icon.png"))); // NOI18N
        btnUpdate.setText("Cập nhật");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 450, 120, 40));
        getContentPane().add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 650, 10));

        cbxMinMax.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cbxMinMax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LỚN NHẤT", "NHỎ NHẤT" }));
        getContentPane().add(cbxMinMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 260, -1, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1270, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeActionPerformed

    private void btnResetAddbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetAddbillActionPerformed
        txtCode.setText("");
        txtOldindex.setText("");
        txtNewindex.setText("");
        txtCode.requestFocus();
        j = 1;
        model.setRowCount(0);
        for (int i = 0; i < brr.size(); i++) {
            showTable(brr.get(i));
        }

    }//GEN-LAST:event_btnResetAddbillActionPerformed
    public int count(ArrayList<Bill> brr) {
        int dem = 0;
        for (int i = 0; i < brr.size(); i++) {
            if (txtCode.getText().equals(brr.get(i).getCode())) {
                dem++;
            }
        }
        return dem;

    }
    private void btnAddbillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddbillActionPerformed
        // TODO add your handling code here:
        Bill f = new Bill();
        if (brr.size() == 0) {
            try {
                f.setCode(txtCode.getText());
                f.setType(cbxType.getSelectedItem().toString());
                f.setOldindex(Double.parseDouble(txtOldindex.getText()));
                f.setNewindex(Double.parseDouble(txtNewindex.getText()));
                brr.add(f);
                showTable(f);
                BillList b = new BillList();
                b.SaveBill(brr);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Dữ liệu nhập vào không đúng!!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                txtCode.setText("");
                txtOldindex.setText("");
                txtNewindex.setText("");
                txtCode.requestFocus();
            }
        } else if (brr.size() > 0) {
            if (count(brr) != 0) {
                JOptionPane.showMessageDialog(this, "Mã hóa đơn này đã được sử dụng!!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                txtCode.setText("");
                txtOldindex.setText("");
                txtNewindex.setText("");
                txtCode.requestFocus();
            } else {
                try {
                    f.setCode(txtCode.getText());
                    f.setType(cbxType.getSelectedItem().toString());
                    f.setOldindex(Double.parseDouble(txtOldindex.getText()));
                    f.setNewindex(Double.parseDouble(txtNewindex.getText()));
                    brr.add(f);
                    showTable(f);
                    BillList b = new BillList();
                    b.SaveBill(brr);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Dữ liệu nhập vào không đúng!!", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                    txtCode.setText("");
                    txtOldindex.setText("");
                    txtNewindex.setText("");
                    txtCode.requestFocus();
                }
            }
        }

    }
    int j = 1;

    public void showTable(Bill f) {
        model.addRow(new Object[]{
            j++, f.getCode(), f.getType(), f.getOldindex(), f.getNewindex(), f.Payment()
        });

    }//GEN-LAST:event_btnAddbillActionPerformed


    private void jTable1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jTable1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jTable1AncestorAdded

    private void txtNewindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewindexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewindexActionPerformed

    private void btnDeleteBillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBillActionPerformed
        // TODO add your handling code here:
        String str = txtCodeRemove.getText();
        int dem = 0;
        for (int i = 0; i < brr.size(); i++) {
            if (brr.get(i).getCode().equals(str)) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                brr.remove(i);
                txtCodeRemove.setText("");
                dem++;
//                break;
            }
        }
        j = 1;
        model.setRowCount(0);
        for (int i = 0; i < brr.size(); i++) {
            showTable(brr.get(i));
        }
        BillList f = new BillList();
        f.SaveBill(brr);
        if (dem != 1) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn không tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
            txtCodeRemove.setText("");
            txtCodeRemove.requestFocus();
        }
    }//GEN-LAST:event_btnDeleteBillActionPerformed

    private void txtOldindexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldindexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOldindexActionPerformed

    private void txtCodeRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodeRemoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodeRemoveActionPerformed

    private void btnFindMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindMaxActionPerformed
        // TODO add your handling code here:
        String MinMax = cbxMinMax.getSelectedItem().toString();
        if (MinMax.equals("LỚN NHẤT")) {
            BillList p = new BillList();
            ArrayList<Bill> arr = new ArrayList<>();
            arr = p.MaxPayment(brr);
            j = 1;
            model.setRowCount(0);
            for (int i = 0; i < arr.size(); i++) {
                showTable(arr.get(i));
            }
        } else if (MinMax.equals("NHỎ NHẤT")) {
            BillList p = new BillList();
            ArrayList<Bill> arr = new ArrayList<>();
            arr = p.MinPayment(brr);
            j = 1;
            model.setRowCount(0);
            for (int i = 0; i < arr.size(); i++) {
                showTable(arr.get(i));
            }
        }
    }//GEN-LAST:event_btnFindMaxActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        Menuc1 m = new Menuc1();
        m.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void btncomputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncomputeActionPerformed
        // TODO add your handling code here:
        String type = cbxchecktpye.getSelectedItem().toString();
        long sum = 0;
        for (int i = 0; i < brr.size(); i++) {
            if (brr.get(i).getType().equals(type)) {
                sum += brr.get(i).Payment();
            }
        }
        txtResultSum.setText("" + sum + " VNĐ");
    }//GEN-LAST:event_btncomputeActionPerformed

    private void ResetComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetComputeActionPerformed
        // TODO add your handling code here:

        txtResultSum.setText("");

    }//GEN-LAST:event_ResetComputeActionPerformed
    String codeupdate;
    private void btnsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsearchActionPerformed
        // TODO add your handling code here:
        boolean dem = false;
        for (int i = 0; i < brr.size(); i++) {
            if (txtcodefind.getText().equals(brr.get(i).getCode())) {
                codeupdate = txtcodefind.getText();
                dem = true;
                String resultFindMax = "\t          HÓA ĐƠN " + brr.get(i).getCode()
                        + "\n=================================="
                        + "\n- Loại hóa đơn : " + brr.get(i).getType()
                        + "\n- Chỉ số cũ : " + brr.get(i).getOldindex()
                        + "\n- Chỉ số mới : " + brr.get(i).getNewindex()
                        + "\n- Định mức sử dụng điện (KW) : " + brr.get(i).Norm()
                        + "\n- Chỉ số điện đã sử dụng : " + brr.get(i).UsedElectricalEnergy()
                        + "\n- Số tiền thanh toán : " + brr.get(i).Payment() + " VNĐ";
                txtResultFindBill.setText(resultFindMax);
                j =1;
                model.setRowCount(0);
                showTable(brr.get(i));
            }
        }
        if (dem == false) {
            txtResultFindBill.setText("");
            txtcodefind.setText("");
            txtcodefind.requestFocus();
            JOptionPane.showMessageDialog(this, "Mã hóa đơn không tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnsearchActionPerformed

    private void txtcodefindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodefindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodefindActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtResultFindBill.setText("");
        UpdateBill u = new UpdateBill();
        u.setVisible(true);
        u.checkupadte(brr, codeupdate);
        u.txtHuongDan.setText(" + Bạn đang thực hiện thay đổi mã hóa đơn " + codeupdate + "\n+ Thay đổi các trường cần thay đổi giá trị, các trường không cần thay đổi hãy để TRỐNG !!");

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ResetCompute;
    private javax.swing.JButton btnAddbill;
    private javax.swing.JButton btnDeleteBill;
    private javax.swing.JButton btnFindMax;
    private javax.swing.JButton btnResetAddbill;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btncompute;
    public javax.swing.JButton btnsearch;
    private javax.swing.JComboBox<String> cbxMinMax;
    private javax.swing.JComboBox<String> cbxType;
    private javax.swing.JComboBox<String> cbxchecktpye;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCode;
    private javax.swing.JTextField txtCodeRemove;
    private javax.swing.JTextField txtNewindex;
    private javax.swing.JTextField txtOldindex;
    public javax.swing.JTextArea txtResultFindBill;
    private javax.swing.JTextField txtResultSum;
    private javax.swing.JTextField txtcodefind;
    // End of variables declaration//GEN-END:variables
}
