/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package billmanage;

import java.io.BufferedReader;
import java.io.FileReader;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ACER
 */
public class Menuc1 extends javax.swing.JFrame {

    /**
     * Creates new form Menuc1
     */
    String email;

    public Menuc1() {
        initComponents();
        Login l = new Login();
        this.setLocationRelativeTo(null);
        try {
            FileReader file = new FileReader("user.txt");
            BufferedReader reader = new BufferedReader(file);
            FileReader file2 = new FileReader("pass.txt");
            BufferedReader reader2 = new BufferedReader(file2);
            FileReader file3 = new FileReader("email.txt");
            BufferedReader reader3 = new BufferedReader(file3);
            l.setUser(reader.readLine());
            l.setPass(reader2.readLine());
            email = reader3.readLine();
        } catch (Exception e) {

        }
        txtShowUsername.setText("Xin chào " + l.getUser());
        txtcontact.setText("Liên hệ : " + email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnmenu = new javax.swing.ButtonGroup();
        radioCreateNewData = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        txtShowUsername = new javax.swing.JLabel();
        txtcontact = new javax.swing.JLabel();
        btnedituser = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        radiodanhthu = new javax.swing.JRadioButton();
        radioOldData = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU CHÍNH");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmenu.add(radioCreateNewData);
        radioCreateNewData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioCreateNewData.setForeground(new java.awt.Color(0, 0, 204));
        radioCreateNewData.setText("Sử dụng dữ liệu hóa đỡn đã lưu");
        getContentPane().add(radioCreateNewData, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 130, 250, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoadmin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 101, -1, 191));

        txtShowUsername.setBackground(new java.awt.Color(204, 255, 204));
        txtShowUsername.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtShowUsername.setForeground(new java.awt.Color(0, 0, 204));
        txtShowUsername.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtShowUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 322, 212, 25));

        txtcontact.setBackground(new java.awt.Color(204, 255, 204));
        txtcontact.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        txtcontact.setForeground(new java.awt.Color(0, 0, 204));
        txtcontact.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(txtcontact, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 359, 212, 25));

        btnedituser.setBackground(new java.awt.Color(51, 255, 51));
        btnedituser.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnedituser.setForeground(new java.awt.Color(0, 0, 0));
        btnedituser.setText("Cập nhật thông tin");
        btnedituser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnedituserActionPerformed(evt);
            }
        });
        getContentPane().add(btnedituser, new org.netbeans.lib.awtextra.AbsoluteConstraints(515, 407, 212, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PHẦN MỀM QUẢN LÍ HÓA ĐƠN TIỀN ĐIỆN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(183, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -1, 830, 70));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(204, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Tiếp tục");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Thoát");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnmenu.add(radiodanhthu);
        radiodanhthu.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radiodanhthu.setForeground(new java.awt.Color(0, 204, 0));
        radiodanhthu.setText("Quản lí doanh thu");

        btnmenu.add(radioOldData);
        radioOldData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        radioOldData.setForeground(new java.awt.Color(255, 0, 51));
        radioOldData.setText("Tạo dữ liệu hóa đơn mới ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radioOldData, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(radiodanhthu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addGap(69, 69, 69)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(545, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addComponent(radioOldData)
                .addGap(36, 36, 36)
                .addComponent(radiodanhthu)
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(121, 121, 121))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 830, 380));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (radioCreateNewData.isSelected()) {
            Menu1 m = new Menu1();
            this.setVisible(false);
            m.setVisible(true);
            m.ReadOject();// doc du lieu vao table
        }
        if (radioOldData.isSelected()) {
            Menu2 m = new Menu2();
            this.setVisible(false);
            m.setVisible(true);
        }
        if (radiodanhthu.isSelected()) {
            Revenue f = new Revenue();
            this.setVisible(false);
            f.setVisible(true);
            f.show1();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        int result = JOptionPane.showConfirmDialog(frame,
                "Bạn có chắc chắn muốn thoát phần mềm ?",
                "Xác nhận",
                JOptionPane.YES_NO_OPTION);
        if (result == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnedituserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnedituserActionPerformed
        // TODO add your handling code here:
        updateuser m = new updateuser();
        m.setVisible(true);
    }//GEN-LAST:event_btnedituserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuc1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuc1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnedituser;
    private javax.swing.ButtonGroup btnmenu;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton radioCreateNewData;
    private javax.swing.JRadioButton radioOldData;
    private javax.swing.JRadioButton radiodanhthu;
    private javax.swing.JLabel txtShowUsername;
    private javax.swing.JLabel txtcontact;
    // End of variables declaration//GEN-END:variables
}
